### PR TITLE
Use permanent, public storage instead of temporary, private

### PR DESCRIPTION
**Pull request by physkets**

### CODE REVIEW

**Comment by physkets** [comment]
This should help with https://github.com/zoff99/ToxAndroidRefImpl/issues/23

**Comment by zoff99** [comment]
do you know what this is doing? have you tested it?

**Comment by physkets** [comment]
Nope; I have not tested it. My only understanding is from reading up about it here:  
https://developer.android.com/training/data-storage/files#PublicFiles

**Comment by zoff99** [comment]
this does not make any sense

**Pull request closed without merging**
