### PR TITLE
make dual licensing explicit (since it was always implicity GPLv2 and GPLv3 because of toxcore)

### PR DESCRIPTION
**Pull request by zoff99**

### CODE REVIEW

**Comment by zoff99** [comment]
@gjedeer do you accept this for your contributions?
https://github.com/zoff99/ToxAndroidRefImpl/commits?author=gjedeer

@rainbyte  do you accept this for your contributions?
https://github.com/zoff99/ToxAndroidRefImpl/commits?author=rainbyte

@naxuroqa  do you accept this for your contributions?
https://github.com/zoff99/ToxAndroidRefImpl/commits?author=naxuroqa

@licaon-kter  do you accept this for your contributions?
https://github.com/zoff99/ToxAndroidRefImpl/commits?author=licaon-kter

**Comment by licaon-kter** [comment]
👍

**Comment by zoff99** [comment]
@licaon-kter i made a small change to the text to make it clear its "choose either of the 2 licenses" and not "both must apply"
hope this is still OK for you?

**Comment by licaon-kter** [comment]
As long as it's OSI and/or FSF approved ;)

**Comment by gjedeer** [comment]
Yes i do

**Comment by zoff99** [comment]
no respone from @rainbyte so reverted his contribution
https://github.com/zoff99/ToxAndroidRefImpl/commits?author=rainbyte

**Comment by rainbyte** [comment]
> no respone from @rainbyte so reverted his contribution
> https://github.com/zoff99/ToxAndroidRefImpl/commits?author=rainbyte

sorry for the late response, I accept the change if not too late

**Comment by zoff99** [comment]
ok now i have reverted the revert of:
https://github.com/zoff99/ToxAndroidRefImpl/commits?author=rainbyte

**Comment by zoff99** [comment]
I am pretty sure @naxuroqa will agree with the dual licensing, so I am going to merge this.
if there is a negative response i will revert his code parts.

**Comment by zoff99** [comment]
rebased it and merging now.

**Pull request merged**
