### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [TRIfA - a Tox Client for Android/Android Application](https://hosted.weblate.org/projects/trifa-a-tox-client-for-android/android-application/).

It also includes following components:

* [TRIfA - a Tox Client for Android/f-droid Texts](https://hosted.weblate.org/projects/trifa-a-tox-client-for-android/f-droid-texts/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by zoff99** [comment]
looking at google translate these changes seem incorrect.

@jiaowobaba02 can you explain what these changes mean?

**Comment by jiaowobaba02** [comment]
I tried the app and found that a lot of it didn't match the environment, so I changed some of the translations

**Comment by jiaowobaba02** [comment]
To be honest, I usually use deepl to check translations

**Comment by jiaowobaba02** [comment]
If you're still in doubt, I'll give you some examples. For example,if you translate (using machine) "peerinfo" into Chinese（对等客户端信息） ,then translate it into English, you'll get "peer client information". It's very strange,and it's strange to our Chinese,too. So I translate it into "Friendinfo"（好友信息）.

**Pull request merged**
