### PR TITLE
Friend list related changes

### PR DESCRIPTION
**Pull request by gjedeer**
I've changed the look of friends/contacts list a bit:
- The 2 status icons have always confused me. I didn't know what they do until I looked at the source. I removed the online icon, used the space to make avatar bigger, and moved the online/offline functionality to user status icon. When user is offline, the user status icon is simply hidden. Alternatively, it could be made gray when user is offline.
- The monospace font for status gave the app a "very much work in progress" feeling. Which is correct in a way, but it's a very usable app despite being work in progress.

Before:
screenshot_20171103-131521

After 1 (EchoBot is offline in this picture):
screenshot_20171103-132049

After 2:
screenshot_20171103-132510

### CODE REVIEW

**Comment by Dako300** [comment]
Looks nice

**Comment by zoff99** [comment]
@gjedeer i don't like the font changes. also not sure about the icon changes.
there has been no feedback about it from any users.

so on hold for now ...

**Comment by gjedeer** [comment]
Yeah i noticed it's on hold ;D

**Comment by NishaYume** [comment]
The icons change looks nice!

The fonts need work, bit better than the default for me

**Comment by Epicalert** [comment]
Looks good, maybe have a gray status icon for offline though?

**Comment by therealmaxmoon** [comment]
I still don't know what those 2 colorful dots mean? 

This new design would be very nice, because it is intuitive and there will be no questions if people see it the first time. 

But the font looks a bit stretched. Would it be so bad to use a normal font? Monospace doesn't look good ether. 

@zoff99 Waiting for feedback might be the wrong strategy. Most users don't even know what github is and if someone knows it, the person wouldn't read every pull request of a software or react to it.

**Comment by zoff99** [comment]
@gjedeer layout has changed already a bit.
the app needs an overhaul in many areas not just the friend list.

**Comment by zoff99** [comment]
any android designers wanting to give it a try ... ?

**Comment by WNemencha** [comment]
Doesn't follow material design... You could reduce avatar size to 48px, status icon to 8-12px, add 16px between avatar+status and texts. Also make sure you have a 8px padding inside the item card, remove the shadow, and the big borders too as they make the list hard to scan. 

Can send a mockup if needed

**Comment by zoff99** [comment]
@WNemencha the design has changed a bit since that PR was opened.
maybe you can start a new PR with a better more modern design for the main friendlist?
would be cool.

**Comment by zoff99** [comment]
now we already have text and audio groups in the list.
and a marking if the friend is connected to us via TCP or UDP (or ToxProxy)

**Comment by WNemencha** [comment]
Will do some mockups tonight, let you know once In have a nice file to present

**Comment by zoff99** [comment]
@WNemencha any progress on this topic?

**Comment by zoff99** [comment]
closing this because of no new activity

**Pull request closed without merging**
