### PR TITLE
Add Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by linsui**

### CODE REVIEW

**Comment by zoff99** [comment]
@linsui you need to provide all the files in the metadata directory for f-droid to work properly

**Comment by linsui** [comment]
@zoff99 Done, thanks!

**Comment by zoff99** [comment]
@linsui you have a typo in the filename:

```android-refimpl-app/app/src/main/res/velues-zh-rCN/strings.xml```

```velues -> values```

**Comment by zoff99** [comment]
i still need to wait for somebody from the TokTok team to verify the chinese texts, since i don't know if they are ok or contain some bad words ...

**Pull request merged**
