### PR TITLE
Add Import/Export section to README.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Link for rendered version https://github.com/xliiv/ToxAndroidRefImpl/tree/imp-exp-section#importexport

**Comment by zoff99** [comment]
@xliiv can you please add it to a seperate MD file?
and the just add the link to that file in the main readme.

**Comment by ghost** [comment]
Sure, done :+1:

**Comment by zoff99** [comment]
i think the main readme needs a cleanup anyway. its overloaded with stuff.

**Comment by zoff99** [comment]
@xliiv do you want to help cleanup the main README aswell? and make it look better.

**Comment by zoff99** [comment]
@xliiv maybe just also add the the chats and group chats are not lost. one can export them all and also all files.
there is just no method to import them again at this time

**Comment by ghost** [comment]
> @xliiv do you want to help cleanup the main README aswell? and make it look better.

Sure but can't say when, so ..

> @xliiv maybe just also add the the chats and group chats are not lost. one can export them all and also all files.
there is just no method to import them again at this time

Some could think that "if it's not importable, then it's lost in terms of recovery", but agree it's better to have it in exported file than nothing.

I can update it while doing readme cleanup.

**Comment by zoff99** [comment]
no hurry. any help welcome ...

**Comment by ghost** [comment]
Just saw the `README.md` file already got some clean-up. Now, it's way better :+1: 

Is there anything else which i could do (similar to readme reorganisation :) )?

**Comment by zoff99** [comment]
maybe a nice help page? explaining what the colored circles mean and any functions that may be not immediately clear to users.
anything that you think is needed? just go ahead and make a PR

**Pull request merged**
